# Generated by Django 5.0.3 on 2024-04-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0002_activeusercounter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveUserCounter',
        ),
    ]
