# Generated by Django 5.0.3 on 2024-04-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0003_delete_activeusercounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='response_time',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
