# Generated by Django 5.0.3 on 2024-04-16 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0005_logentry_exception_logentry_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='exception',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='function_name',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='line_number',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='query_params',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='traceback',
        ),
    ]
