# Generated by Django 5.0.3 on 2024-05-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0006_remove_logentry_exception_remove_logentry_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
